### ISSUE TITLE
SEC_1 和SEC_2 这两个参数是如何提取的？

### ISSUE THREAD

**Issue by owen800q** [apknet/VideoHelper#1]
提取B站的aid和ep 都要用到这两个参数拼接，爬了下官方的JS，没找到算法

**Comment by asche910** [comment]
现在所有的数据在播放页面未经渲染的源代码中可以直接看到， 客户端好像查看不到那些加密的信息，似乎在服务器端就完成了。为了方便起见，我那里就参考了python的you-get源代码

**Comment by owen800q** [comment]
> 现在所有的数据在播放页面未经渲染的源代码中可以直接看到， 客户端好像查看不到那些加密的信息，似乎在服务器端就完成了。为了方便起见，我那里就参考了python的you-get源代码

懂了，谢谢
